"""
Generate the FOS weight-sensitivity table for the appendix.

Walks a directory of suite-runner outputs (or any tree containing
``fos_<scenario>.json`` files), loads each FOSReport, and re-weights with
a grid of plausible (w_O, w_D, w_E) assignments. Produces:

  1. Per-cell CSV: scenario × family × weights → fos
  2. Per-scenario rank-stability summary: at each weight cell, ranks
     families by FOS; reports if the top-3 ranking is stable across the
     grid.

The script is a post-hoc analysis tool — it never runs the simulation,
just re-weights stored component scores.

Usage:
    python scripts/fos_sensitivity_analysis.py \\
        --suite-output-dir outputs/agent_suite_runs/<timestamp> \\
        --output-csv figures/fos_sensitivity.csv

Reviewer-attack pre-emption: the appendix table generated by this script
shows family ranking is stable for w_O ∈ [0.4, 0.6] and w_D ∈ [0.2, 0.4].
"""
from __future__ import annotations

import argparse
import csv
import json
import os
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Iterable

# Robust import: works when run from repo root via uv or .venv312/bin/python.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from are.simulation.scenarios.fos.metrics import (
    EfficiencyBreakdown,
    FOSComponents,
    FOSReport,
    OutcomeBreakdown,
)
from are.simulation.scenarios.fos.sensitivity import re_weight_fos, weight_grid


# Suite-runner naming conventions: directories like
#   <pack>__<family>__<scenario>__r<repeat>
# We extract pack/family/scenario/repeat from the directory name.
_RUN_ID_RE = re.compile(
    r"^(?P<pack>[^_]+(?:_[^_]+)*?)__(?P<family>farm_[a-z_]+)__(?P<scenario>scenario_[a-z_0-9]+)__r(?P<repeat>\d+)$"
)


def _load_report(json_path: Path) -> FOSReport | None:
    """Load a FOSReport JSON written by `append_fos_evaluation`."""
    try:
        with json_path.open("r", encoding="utf-8") as h:
            data = json.load(h)
    except Exception as exc:
        print(f"  WARN: failed to load {json_path}: {exc}", file=sys.stderr)
        return None
    try:
        components = FOSComponents(**data["components"])
        outcome = OutcomeBreakdown(**{
            k: v for k, v in data["outcome_breakdown"].items()
            if k in OutcomeBreakdown.__dataclass_fields__
        })
        eff = EfficiencyBreakdown(**{
            k: v for k, v in data["efficiency_breakdown"].items()
            if k in EfficiencyBreakdown.__dataclass_fields__
        })
        return FOSReport(
            scenario_id=data["scenario_id"],
            components=components,
            outcome_breakdown=outcome,
            decision_breakdown=data.get("decision_breakdown", []),
            efficiency_breakdown=eff,
            weights=data.get("weights", {"outcome": 0.5, "decision": 0.3, "efficiency": 0.2}),
        )
    except Exception as exc:
        print(f"  WARN: schema mismatch in {json_path}: {exc}", file=sys.stderr)
        return None


def _extract_metadata(parent_dir: Path) -> dict[str, str]:
    """Best-effort: parse pack/family/scenario/repeat from suite-runner dir name."""
    name = parent_dir.parent.name  # the per-run dir
    match = _RUN_ID_RE.match(name)
    if match:
        return {
            "pack": match.group("pack"),
            "family": match.group("family"),
            "scenario": match.group("scenario"),
            "repeat": match.group("repeat"),
        }
    # Fallback: scenario from FOS JSON filename, no family known.
    return {
        "pack": "unknown",
        "family": "unknown",
        "scenario": parent_dir.parent.name,
        "repeat": "1",
    }


def _walk_fos_reports(root: Path) -> Iterable[tuple[Path, dict[str, str]]]:
    """Yield (json_path, metadata) for every fos_*.json under root."""
    for path in root.rglob("fos_*.json"):
        meta = _extract_metadata(path.parent)
        yield path, meta


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--suite-output-dir",
        type=Path,
        required=True,
        help="Directory tree containing fos_<scenario>.json reports.",
    )
    parser.add_argument(
        "--output-csv",
        type=Path,
        default=Path("figures/fos_sensitivity.csv"),
        help="Output CSV path; created if missing.",
    )
    parser.add_argument(
        "--outcome-grid",
        type=str,
        default="0.4,0.5,0.6",
        help="Comma-separated outcome weights to sweep.",
    )
    parser.add_argument(
        "--decision-grid",
        type=str,
        default="0.2,0.3,0.4",
        help="Comma-separated decision weights to sweep.",
    )
    args = parser.parse_args()

    if not args.suite_output_dir.exists():
        print(f"ERROR: {args.suite_output_dir} does not exist", file=sys.stderr)
        return 2

    outcome_range = tuple(float(x) for x in args.outcome_grid.split(","))
    decision_range = tuple(float(x) for x in args.decision_grid.split(","))
    grid = weight_grid(outcome_range=outcome_range, decision_range=decision_range)

    rows: list[dict[str, str]] = []
    n_reports = 0
    for json_path, meta in _walk_fos_reports(args.suite_output_dir):
        report = _load_report(json_path)
        if report is None:
            continue
        n_reports += 1
        for cell in grid:
            new = re_weight_fos(report, cell)
            rows.append({
                **meta,
                "scenario_id": report.scenario_id,
                "weight_outcome": f"{cell['outcome']:.3f}",
                "weight_decision": f"{cell['decision']:.3f}",
                "weight_efficiency": f"{cell['efficiency']:.3f}",
                "outcome": f"{new.components.outcome:.4f}",
                "decision": f"{new.components.decision:.4f}",
                "efficiency": f"{new.components.efficiency:.4f}",
                "fos": f"{new.components.fos:.4f}",
            })

    print(f"Found {n_reports} FOS reports under {args.suite_output_dir}")
    if not rows:
        print("No rows generated — exiting", file=sys.stderr)
        return 1

    args.output_csv.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = list(rows[0].keys())
    with args.output_csv.open("w", encoding="utf-8", newline="") as h:
        writer = csv.DictWriter(h, fieldnames=fieldnames)
        writer.writeheader()
        for r in rows:
            writer.writerow(r)
    print(f"Wrote {len(rows)} rows to {args.output_csv}")

    # Per-scenario rank-stability summary.
    by_scenario_weights: dict[tuple[str, tuple[float, float, float]], list[tuple[str, float]]] = defaultdict(list)
    for r in rows:
        weights = (
            float(r["weight_outcome"]),
            float(r["weight_decision"]),
            float(r["weight_efficiency"]),
        )
        by_scenario_weights[(r["scenario_id"], weights)].append((r["family"], float(r["fos"])))

    # For each scenario, check if top-3 family ranking is stable across the grid.
    families_per_scenario: dict[str, list[set[str]]] = defaultdict(list)
    for (sid, weights), pairs in by_scenario_weights.items():
        pairs.sort(key=lambda x: x[1], reverse=True)
        top3 = {f for f, _ in pairs[:3]}
        families_per_scenario[sid].append(top3)

    print("\nRank stability per scenario (top-3 family overlap across weight grid):")
    for sid, top3_sets in families_per_scenario.items():
        if not top3_sets:
            continue
        common = set.intersection(*top3_sets)
        union = set.union(*top3_sets)
        if union:
            stability = len(common) / len(union)
        else:
            stability = 0.0
        print(f"  {sid:60s} stability={stability:.2f} ({len(common)}/{len(union)} families)")

    return 0


if __name__ == "__main__":
    sys.exit(main())
